const initialData = {
  tasks: {
    "item-1": { id: "item-1", content: "cookie" },
    "item-2": { id: "item-2", content: "bear claw" },
    "item-3": { id: "item-3", content: "brownie" },
    "item-4": { id: "item-4", content: "Tart" },
    "item-5": { id: "item-5", content: "Jelly-o" },
    "item-6": { id: "item-6", content: "Cheesecake" },
  },
  columns: {
    "calendar-1": {
      id: "calendar-1",
      title: "Day 1",
      taskIds: ["item-1", "item-2"],
    },
    "calendar-2": {
      id: "calendar-2",
      title: " Day 2",
      taskIds: ["item-3", "item-4"],
    },
    "calendar-3": {
      id: "calendar-3",
      title: " Day 3",
      taskIds: [],
    },
    "calendar-4": {
      id: "calendar-4",
      title: " Day 4",
      taskIds: [],
    },
    "calendar-5": {
      id: "calendar-5",
      title: " Day 5",
      taskIds: [],
    },
    "calendar-6": {
      id: "calendar-6",
      title: " Day 6",
      taskIds: ["item-5", "item-6"],
    },
    "calendar-7": {
      id: "calendar-7",
      title: " Day 7",
      taskIds: [],
    },
    "calendar-8": {
      id: "calendar-8",
      title: " Day 8",
      taskIds: [],
    },
    "calendar-9": {
      id: "calendar-9",
      title: " Day 9",
      taskIds: [],
    },
    "calendar-10": {
      id: "calendar-10",
      title: " Day 10",
      taskIds: [],
    },
    "calendar-11": {
      id: "calendar-11",
      title: " Day 11",
      taskIds: [],
    },
    "calendar-12": {
      id: "calendar-12",
      title: " Day 12",
      taskIds: [],
    },
    "calendar-13": {
      id: "calendar-13",
      title: " Day 13",
      taskIds: [],
    },
    "calendar-14": {
      id: "calendar-14",
      title: " Day 14",
      taskIds: [],
    },
    "calendar-15": {
      id: "calendar-15",
      title: " Day 15",
      taskIds: [],
    },
    "calendar-16": {
      id: "calendar-16",
      title: " Day 16",
      taskIds: [],
    },
    "calendar-17": {
      id: "calendar-17",
      title: " Day 17",
      taskIds: [],
    },
    "calendar-18": {
      id: "calendar-18",
      title: " Day 18",
      taskIds: [],
    },
    "calendar-19": {
      id: "calendar-19",
      title: " Day 19",
      taskIds: [],
    },
    "calendar-20": {
      id: "calendar-20",
      title: " Day 20",
      taskIds: [],
    },
    "calendar-21": {
      id: "calendar-21",
      title: " Day 21",
      taskIds: [],
    },
    "calendar-22": {
      id: "calendar-22",
      title: " Day 22",
      taskIds: [],
    },
    "calendar-23": {
      id: "calendar-23",
      title: " Day 23",
      taskIds: [],
    },
    "calendar-24": {
      id: "calendar-24",
      title: " Day 24",
      taskIds: [],
    },
    "calendar-25": {
      id: "calendar-25",
      title: " Day 25",
      taskIds: [],
    },
    "calendar-26": {
      id: "calendar-26",
      title: " Day 26",
      taskIds: [],
    },
    "calendar-27": {
      id: "calendar-27",
      title: " Day 27",
      taskIds: [],
    },
    "calendar-28": {
      id: "calendar-28",
      title: " Day 28",
      taskIds: [],
    },
    "calendar-29": {
      id: "calendar-29",
      title: " Day 29",
      taskIds: [],
    },
    "calendar-30": {
      id: "caledar-30",
      title: " Day 30",
      taskIds: [],
    },
  },

  columnOrder: [
    "calendar-1",
    "calendar-2",
    "calendar-3",
    "calendar-4",
    "calendar-5",
    "calendar-6",
    "calendar-7",
    "calendar-8",
    "calendar-9",
    "calendar-10",
    "calendar-11",
    "calendar-12",
    "calendar-13",
    "calendar-14",
    "calendar-15",
    "calendar-16",
    "calendar-17",
    "calendar-18",
    "calendar-19",
    "calendar-20",
    "calendar-21",
    "calendar-22",
    "calendar-23",
    "calendar-24",
    "calendar-25",
    "calendar-26",
    "calendar-27",
    "calendar-28",
    "calendar-29",
    "calendar-30",
  ],
};

export default initialData;
